name: fuzzer

on:
  pull_request:
    branches: [ "master" ]
  push:
    branches: [ "master" ]

env:
  BUILD_TYPE: Debug
  CC: /usr/bin/clang
  
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Install deps
      run: |
        sudo apt-get update
        sudo apt-get install libpcap-dev cmake clang

    - name: Configure Fuzzing
      run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} -D BUILD_FUZZER=ON

    - name: Build Fuzzer
      run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}} -v

    - name: Run fuzzer sentry pcap
      run: ${{github.workspace}}/build/fuzz_sentry_pcap -max_total_time=60 ${{github.workspace}}/tests/fuzzing/corpus_sentry_pcap

    - name: Run fuzzer sentry stealth
      run: ${{github.workspace}}/build/fuzz_sentry_stealth -max_total_time=60 ${{github.workspace}}/tests/fuzzing/corpus_sentry_raw
