name: System Tests

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  BUILD_TYPE: Debug

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Install pcap
      run: |
        sudo apt-get update
        sudo apt-get install libpcap-dev nmap

    - name: Configure CMake
      run: cmake -B ${{github.workspace}}/debug -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}

    - name: Build
      run: cmake --build ${{github.workspace}}/debug --config ${{env.BUILD_TYPE}}

    - name: System Test
      run: |
        cd system_test
        sudo ./run_all_tests.sh
